/** @type {import("tailwindcss").Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue",
  ],
  safelist: [
    "bg-mercury",
    "bg-venus",
    "bg-earth",
    "bg-mars",
    "bg-jupiter",
    "bg-saturn",
    "bg-uranus",
    "bg-neptune",
    "border-b-mercury",
    "border-b-venus",
    "border-b-earth",
    "border-b-mars",
    "border-b-jupiter",
    "border-b-saturn",
    "border-b-uranus",
    "border-b-neptune",
    "border-t-mercury",
    "border-t-venus",
    "border-t-earth",
    "border-t-mars",
    "border-t-jupiter",
    "border-t-saturn",
    "border-t-uranus",
    "border-t-neptune",
  ],
  theme: {
    extend: {
      screens: {
        xl: "1024px",
        md: "667px",
        sm: "420px",
        xs: "0px",
      },
      colors: {
        white: "#fff",
        dark: "#070724",
        graylight: "#838391",
        graydark: "#28284f",
        mercury: "#419ebb",
        venus: "#eda249",
        earth: "#6d2ed5",
        mars: "#d14c32",
        jupiter: "#d83a34",
        saturn: "#cd5120",
        uranus: "#1ec1a1",
        neptune: "#2d68f0",
        "white-20%": "rgba(255, 255, 255, 0.2)",
      },
      fontFamily: {
        spartan: [
          "League Spartan",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"'
        ],
        antonio: [
          "Antonio",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"'
        ],
      },
      fontSize: {
        h1: ["5rem", { lineHeight: "6.4375rem" }],
        h2: ["2.5rem", { lineHeight: "3.25rem" }],
        h3: ["0.75rem", { lineHeight: "1.5625rem" }],
        h4: ["0.6875rem", { lineHeight: "1.5625rem" }],
        p: ["0.875rem", { lineHeight: "1.5625rem" }],
      },
      letterSpacing: {
        h2: "-.04em",
        h3: ".16em",
        h4: ".06em",
      },
      container: {
        center: true,
        screens: {
          sm: "668px",
          md: "768px",
          lg: "960px",
          xl: "1110px",
        },
      },
    },
  },
  plugins: [],
}
